export const SEO_KEYWORDS = {
  casasPrefabricadas: [
    "casas prefabricadas",
    "casas prefabricadas chile",
    "casas prefabricadas chile precios",
    "venta de casas prefabricadas",
    "comprar casa prefabricada chile",
    "constructoras casas prefabricadas",
    "prefabricadas chile",
    "casas prefabricadas modernas",
    "construccion de casas prefabricadas",
    "construir casa prefabricada",
  ],
  casasSip: [
    "casas paneles sip",
    "casas sip",
    "casas sip chile",
    "casas prefabricadas sip",
    "casas prefabricadas paneles sip",
    "panel sip chile",
    "precio casas sip chile",
    "ventajas casas sip",
    "construir casa sip",
    "comprar casa sip",
    "modelos casas sip",
  ],
  casasModulares: [
    "casas modulares",
    "casas modulares chile",
    "casas prefabricadas modulares",
    "precio casas modulares",
    "casa modular chile",
    "modelos casas modulares",
    "casas modulares prefabricadas",
    "casas modulares llave en mano",
  ],
  modelosPrefabricadas: [
    "modelos casas prefabricadas",
    "modelos de casas prefabricadas chile",
    "catalogo casas prefabricadas",
    "planos casas prefabricadas",
    "precios casas prefabricadas chile",
    "modelos de casas sip",
    "modelos casas modulares",
    "casas prefabricadas de 2 dormitorios",
    "modelo casa prefabricada",
  ],
  tinyHouse: [
    "tiny house chile",
    "construir tiny house",
    "comprar casa tiny house",
    "tiny house llave en mano",
    "tiny house chile precio",
    "mini casas prefabricadas",
  ],
  seguimientoObras: [
    "sistema de seguimiento de obras",
    "seguimiento de obra online",
    "avance de construccion",
    "control de obra digital",
    "bitacora de obra",
    "seguimiento de proyecto de construccion",
    "control de avance de obra",
    "plataforma de seguimiento de obras",
  ],
} as const;

