INSERT INTO public.constructoras (nombre, slug, regiones, email, sitio_web, telefono, plan, verificada, score_confianza) VALUES
  ('Aliro Cardenas', 'aliro-cardenas-283', '{}', NULL, 'alirocardenas.cl', NULL, 'informativo', false, 0),
  ('Arkubic', 'arkubic-391', '{}', NULL, 'arkubic.cl', '+56 7821 6360', 'informativo', false, 0),
  ('Arqydom', 'arqydom-743', '{Metropolitana}', NULL, 'arqydom.cl', NULL, 'informativo', false, 0),
  ('Autónoma Modulares', 'aut-noma-modulares-381', '{}', 'contacto@autonomamodulares.cl', 'autonomamodulares.cl', '+56 5229 8883', 'informativo', false, 0),
  ('BIOBIO MADERA', 'biobio-madera-743', '{Biobío}', 'contacto@biobiomadera.cl', 'biobiomadera.cl', NULL, 'informativo', false, 0),
  ('Biourban', 'biourban-472', '{}', NULL, 'biourban.cl', NULL, 'informativo', false, 0),
  ('Box Panel Chile', 'box-panel-chile-659', '{}', 'ventas@boxpanelchile.cl', 'boxpanelchile.cl', '+56 9328 9173', 'informativo', false, 0),
  ('Casa de Madera', 'casa-de-madera-549', '{}', 'contacto@casademadera.cl', 'casademadera.cl', '+56 3946 4346', 'informativo', false, 0),
  ('Casa Prefabricada Chile', 'casa-prefabricada-chile-824', '{}', NULL, 'casaprefabricada.cl', NULL, 'informativo', false, 0),
  ('Casas 7 Lagos', 'casas-7-lagos-789', '{}', NULL, 'casas7lagos.cl', NULL, 'informativo', false, 0),
  ('Casas Alvarado', 'casas-alvarado-922', '{}', 'contacto@casasalvarado.cl', 'casasalvarado.cl', '+56 41629375', 'informativo', false, 0),
  ('Casas Andes', 'casas-andes-985', '{Metropolitana}', 'contacto@vpandes.cl', 'casasandes.cl', '+56 8843 2545', 'informativo', false, 0),
  ('Casas Arbolito', 'casas-arbolito-602', '{}', NULL, 'casasarbolito.cl', '+56 5188 8397', 'informativo', false, 0),
  ('Casas Azocar', 'casas-azocar-605', '{}', 'info@casasazocar.cl', 'casasazocar.cl', '+56 8419 1774', 'informativo', false, 0),
  ('Casas Baeza', 'casas-baeza-351', '{}', 'ventas@casasbaeza.cl', 'casasbaeza.cl', '+56 6900 2863', 'informativo', false, 0),
  ('Casas Bio Bio', 'casas-bio-bio-571', '{Biobío}', 'contacto@casasbiobio.cl', 'casasbiobio.cl', '+56 77080036', 'informativo', false, 0),
  ('Casas Chile', 'casas-chile-658', '{Aysén}', NULL, 'casaschilespa.cl', '+56 6765 2158', 'informativo', false, 0),
  ('Casas Chiloé', 'casas-chilo-445', '{Los Lagos}', 'casaschiloe@gmail.com', 'casaschiloe.cl', '+56 34094385', 'informativo', false, 0),
  ('Casas Containers', 'casas-containers-957', '{Metropolitana}', 'contacto@casascontainers.cl', 'casascontainers.cl', '+56 4918 7414', 'informativo', false, 0),
  ('CASAS Copiapó', 'casas-copiap-986', '{Metropolitana}', 'contacto@casascopiapo.cl', 'casascopiapo.cl', '+56 7426 4545', 'informativo', false, 0),
  ('Casas De La Costa', 'casas-de-la-costa-841', '{}', 'contacto@casasdelacosta.cl', 'casasdelacosta.cl', '+56 9744 6775', 'informativo', false, 0),
  ('Casas De Metalcom', 'casas-de-metalcom-433', '{}', 'info@casasnordicas.cl', 'casasnordicas.cl', '+56 2228 8402', 'informativo', false, 0),
  ('Casas El Litoral', 'casas-el-litoral-935', '{}', NULL, 'casasprefabricadasellitoral.cl', '+56 8836 9466', 'informativo', false, 0),
  ('Casas El Mirador', 'casas-el-mirador-365', '{Maule}', 'contacto@casaselmirador.cl', 'casaselmirador.cl', '+56 81319228', 'informativo', false, 0),
  ('Casas Fabelsa', 'casas-fabelsa-70', '{}', 'constructorafabelsa@gmail.com', 'casasfabelsa.cl', '+56 8948 5227', 'informativo', false, 0),
  ('Casas Green Valley', 'casas-green-valley-200', '{}', 'contacto@casasgreenvalley.cl', 'casasgreenvalley.cl', '+56 2583 2001', 'informativo', false, 0),
  ('Casas Laguna', 'casas-laguna-762', '{}', 'contacto@casaslaguna.cl', 'casaslaguna.cl', '+56 4856 5620', 'informativo', false, 0),
  ('Casas Lanco', 'casas-lanco-355', '{Biobío}', NULL, 'casaslanco.cl', NULL, 'informativo', false, 0),
  ('Casas Lihuel', 'casas-lihuel-344', '{}', NULL, 'casaslihuel.cl', '+56 64591125', 'informativo', false, 0),
  ('Casas Linares', 'casas-linares-616', '{Maule}', 'maderasboada@hotmail.com', 'casaslinares.cl', '+56 96999011', 'informativo', false, 0),
  ('Casas Lo Infante', 'casas-lo-infante-737', '{}', NULL, 'casasloinfante.cl', '+56 83416889', 'informativo', false, 0),
  ('Casas Longavi', 'casas-longavi-54', '{}', 'contacto@casaslongavi.cl', 'casaslongavi.cl', '+56 20219081', 'informativo', false, 0),
  ('Casas METALKIT', 'casas-metalkit-351', '{Atacama}', 'ventas@metalkit.cl', 'casasprefabricadascf.cl', '+56 5805 6559', 'informativo', false, 0),
  ('Casas Modulares', 'casas-modulares-180', '{}', 'contacto@modul.cl', 'modul.cl', '+56 2214 5935', 'informativo', false, 0),
  ('Casas Modulares', 'casas-modulares-889', '{}', 'contacto@domohabitare.cl', 'domohabitare.cl', '+56 61405906', 'informativo', false, 0),
  ('Casas Modulares', 'casas-modulares-375', '{Metropolitana}', 'ventas@constructoraubel.cl', 'constructoraubel.cl', '+56 9871 3705', 'informativo', false, 0),
  ('Casas O''higgins', 'casas-o-higgins-680', '{O''Higgins}', 'ventas@casasohiggins.cl', 'casasohiggins.cl', '+56 22753385', 'informativo', false, 0),
  ('Casas Pancer', 'casas-pancer-948', '{Metropolitana}', 'ventas@casaspancer.cl', 'casaspancer.cl', '+56 9730 5174', 'informativo', false, 0),
  ('CASAS PREFABRICADAS', 'casas-prefabricadas-366', '{Los Ríos}', '56930282442contacto@casasprefabricadasval', 'divia.cl', '+56 30282442', 'informativo', false, 0),
  ('Casas Prefabricadas', 'casas-prefabricadas-23', '{}', 'info@casasprefabricadas.cl', 'casasprefabricadas.cl', NULL, 'informativo', false, 0),
  ('Casas Prefabricadas', 'casas-prefabricadas-806', '{Metropolitana}', 'contacto@casasanalberto.com', 'casasanalberto.com', '+56 44081159', 'informativo', false, 0),
  ('Casas Prefabricadas', 'casas-prefabricadas-902', '{Los Lagos}', 'info@ecoframe.cl', 'ecoframe.cl', NULL, 'informativo', false, 0),
  ('Casas Prefabricadas', 'casas-prefabricadas-809', '{}', 'ventas@trebolspa.cl', 'trebolspa.cl', '+56 32434267', 'informativo', false, 0),
  ('Casas Prefabricadas Antilhue', 'casas-prefabricadas-antilhue-538', '{Biobío}', NULL, 'casasantilhue.cl', NULL, 'informativo', false, 0),
  ('Casas Prefabricadas Chile', 'casas-prefabricadas-chile-657', '{Los Lagos}', 'contacto@casasprefabricadaschile.cl', 'casasprefabricadaschile.cl', NULL, 'informativo', false, 0),
  ('Casas Prefabricadas Chile', 'casas-prefabricadas-chile-570', '{}', NULL, 'casasprefabricadasenchile.com', NULL, 'informativo', false, 0),
  ('Casas Prefabricadas Curicó', 'casas-prefabricadas-curic-128', '{Maule}', NULL, 'construex.cl', '+56 35661495', 'informativo', false, 0),
  ('Casas Prefabricadas Del Lago', 'casas-prefabricadas-del-lago-882', '{Metropolitana}', 'casasdellagochile@gmail.com', 'casasdellago.cl', NULL, 'informativo', false, 0),
  ('Casas Prefabricadas Del Maule', 'casas-prefabricadas-del-maule-852', '{Maule}', NULL, 'casas-prefabricadas-del-maule.ueniweb.com', '+56 89111078', 'informativo', false, 0),
  ('Casas Prefabricadas El Alba', 'casas-prefabricadas-el-alba-858', '{Metropolitana}', '8761contacto@prefabricadaselalba.cl', 'prefabricadaselalba.cl', '+56 5699 8761', 'informativo', false, 0),
  ('Casas Prefabricadas En Chile', 'casas-prefabricadas-en-chile-64', '{Antofagasta}', NULL, 'casaprefabricadachile.cl', NULL, 'informativo', false, 0),
  ('Casas Prefabricadas En Chile', 'casas-prefabricadas-en-chile-970', '{Antofagasta}', NULL, 'casasprenchil.cl', NULL, 'informativo', false, 0),
  ('Casas Prefabricadas Foresco Spa', 'casas-prefabricadas-foresco-spa-738', '{Maule}', 'emailcasasforesco@gmail.com', 'foresco.cl', '+56 39319688', 'informativo', false, 0),
  ('Casas Prefabricadas Futrono', 'casas-prefabricadas-futrono-336', '{Metropolitana}', 'ejecutivo.ventas@prefabricadasfutrono.cl', 'prefabricadasfutrono.cl', '+56 53219734', 'informativo', false, 0),
  ('Casas Prefabricadas Green Valley', 'casas-prefabricadas-green-valley-98', '{}', 'contacto@cprefabricadas.cl', 'cprefabricadas.cl', '+56 2583 2001', 'informativo', false, 0),
  ('Casas Prefabricadas Imperio', 'casas-prefabricadas-imperio-777', '{}', 'info@casasprefabricadasimperio.cl', 'casasprefabricadasimperio.cl', '+56 41252687', 'informativo', false, 0),
  ('CASAS PREFABRICADAS KRATER', 'casas-prefabricadas-krater-26', '{La Araucanía}', '976695286ana.p@casaskratercl.io', 'casaskratercl.io', '+56 76695286', 'informativo', false, 0),
  ('Casas Prefabricadas La Capilla', 'casas-prefabricadas-la-capilla-939', '{}', NULL, 'casaslacapilla.cl', '+56 73301380', 'informativo', false, 0),
  ('Casas Prefabricadas La Minga', 'casas-prefabricadas-la-minga-61', '{}', 'proyectoinfo@casasminga.com', 'casaslaminga.cl', '+56 4095 7264', 'informativo', false, 0),
  ('Casas Prefabricadas Limache', 'casas-prefabricadas-limache-282', '{}', NULL, 'casaslimache.cl', '+56 7551 0394', 'informativo', false, 0),
  ('Casas Prefabricadas Mar Y Sol', 'casas-prefabricadas-mar-y-sol-980', '{}', NULL, 'constructora-csq.webnode.cl', '+56 92871653', 'informativo', false, 0),
  ('Casas Prefabricadas Premium', 'casas-prefabricadas-premium-640', '{}', NULL, 'casasvichuquen.cl', NULL, 'informativo', false, 0),
  ('Casas Prefabricadas Punta Arenas', 'casas-prefabricadas-punta-arenas-148', '{Magallanes}', NULL, 'listado.mercadolibre.cl', NULL, 'informativo', false, 0),
  ('Casas Prefabricadas Ramirez', 'casas-prefabricadas-ramirez-550', '{Metropolitana}', NULL, 'casasprefabricadasramirez.ueniweb.com', '+56 4451 7466', 'informativo', false, 0),
  ('Casas Prefabricadas Río Bueno', 'casas-prefabricadas-r-o-bueno-268', '{}', NULL, 'casasriobueno.cl', '+56 9196 1165', 'informativo', false, 0),
  ('Casas Prefabricadas Riqueval', 'casas-prefabricadas-riqueval-30', '{Metropolitana}', 'ventas@riqueval.cl', 'riqueval.cl', '+56 87681615', 'informativo', false, 0),
  ('Casas Prefabricadas Vespucio', 'casas-prefabricadas-vespucio-913', '{}', NULL, 'casasvespucio.cl', '+56 73723093', 'informativo', false, 0),
  ('CASAS PREFABRICADAS Y TRANSPORTES', 'casas-prefabricadas-y-transportes-756', '{TORRES}', 'tucomercio@coyhaique.cl', 'tucomercio@coyhaique.cl', '+56 47581463', 'informativo', false, 0),
  ('Casas Pucon Constructora', 'casas-pucon-constructora-755', '{La Araucanía}', NULL, 'casaspucon.cl', NULL, 'informativo', false, 0),
  ('Casas Quinchilca', 'casas-quinchilca-354', '{Biobío}', 'contacto@casasquinchilca.cl', 'casasquinchilca.cl', NULL, 'informativo', false, 0),
  ('Casas Resort', 'casas-resort-533', '{}', NULL, 'casasresort.cl', '+56 6630 2290', 'informativo', false, 0),
  ('Casas Sandoval', 'casas-sandoval-285', '{Metropolitana}', NULL, 'casassandoval.cl', '+56 3100 8214', 'informativo', false, 0),
  ('Casas Sustentables', 'casas-sustentables-687', '{}', NULL, 'construyesustentable.cl', NULL, 'informativo', false, 0),
  ('CASAS VAL', 'casas-val-778', '{}', NULL, 'casasval.cl', NULL, 'informativo', false, 0),
  ('Casas Valles Del Sur', 'casas-valles-del-sur-4', '{}', NULL, 'casasvallesdelsur.cl', NULL, 'informativo', false, 0),
  ('Casas Viento Sur', 'casas-viento-sur-34', '{}', 'info@casasvientosur.cl', 'casasvientosur.cl', '+56 1234 5678', 'informativo', false, 0),
  ('Casasamerica', 'casasamerica-0', '{Metropolitana}', 'info@casascaballero.cl', 'casasamerica.cl', '+56 2310 5779', 'informativo', false, 0),
  ('Casaschilesip', 'casaschilesip-884', '{Metropolitana}', 'info@casaschilespa.cl', 'casaschilesip.cl', '+56 3929 1180', 'informativo', false, 0),
  ('Casascontainers', 'casascontainers-169', '{}', 'chilecontacto@constructainers.cl', 'constructainers.cl', '+56 66023323', 'informativo', false, 0),
  ('Casascubik', 'casascubik-208', '{}', 'info@casascubik.cl', 'casascubik.cl', '+56 90988292', 'informativo', false, 0),
  ('Casascubo', 'casascubo-11', '{Metropolitana}', 'infocasascubo@gmail.com', 'casascubo.cl', NULL, 'informativo', false, 0),
  ('Casur :', 'casur-640', '{}', 'info@casur.cl', 'casur.cl', '+56 2639 2107', 'informativo', false, 0),
  ('Cchc', 'cchc-940', '{}', NULL, 'cchc.cl', NULL, 'informativo', false, 0),
  ('CDC SUMINISTROS', 'cdc-suministros-771', '{Metropolitana}', 'contacto@cdcsuministros.cl', 'cdcsuministros.cl', '+56 3280 2501', 'informativo', false, 0),
  ('Chile Domos', 'chile-domos-549', '{Valparaíso}', '2200contacto@chiledomos.cl', 'chiledomos.cl', '+56 9726 2200', 'informativo', false, 0),
  ('Chile Home', 'chile-home-516', '{}', 'contacto@chilehome.cl', 'chilehome.cl', '+56 2617 8767', 'informativo', false, 0),
  ('Concón Maderas Impregnadas', 'conc-n-maderas-impregnadas-863', '{}', 'info@conconmaderas.cl', 'conconmaderas.cl', '+56 82497552', 'informativo', false, 0),
  ('Construcción De Casas Prefabricadas En', 'construcci-n-de-casas-prefabricadas-en-474', '{Biobío}', 'santamartaltda@gmail.com', 'santamartaltda@gmail.com', '+56 3901', 'informativo', false, 0),
  ('Construcción En Angol', 'construcci-n-en-angol-890', '{La Araucanía}', NULL, 'solucionesintegralesangol.cl', '+56 35172731', 'informativo', false, 0),
  ('Construcción En Vulcometal O Metalcon', 'construcci-n-en-vulcometal-o-metalcon-766', '{}', 'contacto@cintac.cl', 'cintac.cl', '+56 24849200', 'informativo', false, 0),
  ('Construcciones Jpp', 'construcciones-jpp-263', '{Metropolitana}', NULL, 'facebook.com', '+56 44306323', 'informativo', false, 0),
  ('Construccionesprofesionales', 'construccionesprofesionales-646', '{Metropolitana}', NULL, 'construccionesprofesionales.cl', NULL, 'informativo', false, 0),
  ('Construccionindustrializada', 'construccionindustrializada-971', '{}', NULL, 'construccionindustrializada.cl', '+56 2718 7511', 'informativo', false, 0),
  ('Construkit', 'construkit-592', '{}', NULL, 'construkit.cl', '+56 9647 6004', 'informativo', false, 0),
  ('Construyetudomo', 'construyetudomo-263', '{}', NULL, 'construyetudomo.cl', '+56 5129 0672', 'informativo', false, 0),
  ('Contacto – Casas KIT', 'contacto-casas-kit-82', '{}', 'ventas@casaskit.cl', 'casaskit.cl', '+56 7138 9841', 'informativo', false, 0),
  ('Container World', 'container-world-95', '{}', NULL, 'containerworld.cl', NULL, 'informativo', false, 0),
  ('Containerfull', 'containerfull-632', '{}', 'hola@containerfull.cl', 'containerfull.cl', '+56 30202968', 'informativo', false, 0),
  ('Containerland', 'containerland-630', '{}', 'ventas@containerland.cl', 'containerland.cl', '+56 9224 3796', 'informativo', false, 0),
  ('Containers Patagonia', 'containers-patagonia-954', '{}', NULL, 'containerspatagonia.cl', '+56 2528 6556', 'informativo', false, 0),
  ('Contenedores Alma', 'contenedores-alma-288', '{}', 'ariel.ventas@contenedoresalma.cl', 'contenedoresalma.cl', '+56 65767081', 'informativo', false, 0),
  ('Contenedores Habitacionales En Todo Chile', 'contenedores-habitacionales-en-todo-chile-104', '{}', '17743cveliz@megacontainers.cl', 'megacontainers.cl', NULL, 'informativo', false, 0),
  ('CONTENEDORES MODULARES', 'contenedores-modulares-70', '{}', NULL, 'vimafechile.cl', NULL, 'informativo', false, 0),
  ('Diario Sustentable', 'diario-sustentable-258', '{}', NULL, 'diariosustentable.com', NULL, 'informativo', false, 0),
  ('Domos Del Sur', 'domos-del-sur-530', '{Metropolitana}', '0775contacto@domosdelsur.cl', 'domosdelsur.cl', '+56 2966 0775', 'informativo', false, 0),
  ('Domos Prefabricados', 'domos-prefabricados-137', '{Metropolitana}', '56951134567contacto@domosprefabricados.cl', 'domosprefabricados.cl', '+56 51134567', 'informativo', false, 0),
  ('Domos Quilpué', 'domos-quilpu-137', '{Valparaíso}', NULL, 'domosquilpue.cl', NULL, 'informativo', false, 0),
  ('Domos Valdivia', 'domos-valdivia-469', '{}', NULL, 'domosvaldivia.cl', '+56 71042780', 'informativo', false, 0),
  ('Domoselk', 'domoselk-731', '{Aysén}', 'info@domoselk.com', 'domoselk.com', NULL, 'informativo', false, 0),
  ('Ecomodulares', 'ecomodulares-766', '{Metropolitana}', 'contacto@ecomodulares.cl', 'ecomodulares.cl', NULL, 'informativo', false, 0),
  ('Ehaus', 'ehaus-514', '{}', 'contacto@ehaus.cl', 'ehaus.cl', NULL, 'informativo', false, 0),
  ('El Diario Inmobiliario', 'el-diario-inmobiliario-825', '{Metropolitana}', NULL, 'eldiarioinmobiliario.cl', NULL, 'informativo', false, 0),
  ('EL TOKE LTDA', 'el-toke-ltda-90', '{}', 'info@eltoke.cl', 'eltoke.cl', '+56 7798 3103', 'informativo', false, 0),
  ('Evox House', 'evox-house-395', '{}', 'arenas.contacto@evoxhouse.cl', 'evoxhouse.cl', '+56 2371 0718', 'informativo', false, 0),
  ('Fabrica FV', 'fabrica-fv-449', '{}', 'info@fundacionvivienda.cl', 'fabricafv.cl', '+56 3934 0169', 'informativo', false, 0),
  ('Fábrica Paneles Sip Curicó', 'f-brica-paneles-sip-curic-929', '{Maule}', 'tecnosip@maderasvaldivia.cl', 'tecsip.cl', '+56 2788 6426', 'informativo', false, 0),
  ('Facoro', 'facoro-82', '{Metropolitana}', 'info@facoro.cl', 'facoro.cl', NULL, 'informativo', false, 0),
  ('FEMARQ SPA', 'femarq-spa-949', '{}', 'contacto@femarq.cl', 'femarq.cl', '+56 3778 3954', 'informativo', false, 0),
  ('Fotocasa', 'fotocasa-987', '{}', 'ventas@fotocasa.cl', 'fotocasa.cl', '+56 7611 6990', 'informativo', false, 0),
  ('Globalsip', 'globalsip-249', '{}', 'contacto@globalsip.cl', 'globalsip.cl', '+56 6334 3544', 'informativo', false, 0),
  ('Grau', 'grau-537', '{Metropolitana}', 'contacto@grau.cl', 'grau.cl', '+56 51224403', 'informativo', false, 0),
  ('Grupo Casas O''higgins', 'grupo-casas-o-higgins-746', '{O''Higgins}', NULL, 'cl.linkedin.com', NULL, 'informativo', false, 0),
  ('HCP', 'hcp-697', '{Los Lagos}', 'contacto@hcpcasas.cl', 'hcpcasas.cl', '+56 20991768', 'informativo', false, 0),
  ('Hoteles En Chile', 'hoteles-en-chile-551', '{Metropolitana}', NULL, 'hotelplazacolonarica.cl', NULL, 'informativo', false, 0),
  ('Inmobiliaria Terra Sur', 'inmobiliaria-terra-sur-147', '{Metropolitana}', 'contacto@iterrasur.cl', 'iterrasur.cl', '+56 5007 9928', 'informativo', false, 0),
  ('Innova3', 'innova3-826', '{Biobío}', 'contacto@innova3.cl', 'innova3.cl', '+56 8305 1402', 'informativo', false, 0),
  ('Instagram', 'instagram-718', '{}', NULL, 'instagram.com', NULL, 'informativo', false, 0),
  ('Intercontainers', 'intercontainers-697', '{Metropolitana}', NULL, 'intercontainers.cl', '+56 5879 9619', 'informativo', false, 0),
  ('Jamab', 'jamab-846', '{}', 'hola@jamab.cl', 'jamab.cl', '+56 42513372', 'informativo', false, 0),
  ('KASAKIT SPA', 'kasakit-spa-258', '{}', 'kasakitspa@gmail.com', 'kasakittemuco.com', '+56 6688 5249', 'informativo', false, 0),
  ('L2arquitectura', 'l2arquitectura-522', '{Metropolitana}', NULL, 'l2arquitectura.cl', NULL, 'informativo', false, 0),
  ('La Custre', 'la-custre-36', '{}', 'ventas@casaslacustre.cl', 'casaslacustre.cl', '+56 9039 0773', 'informativo', false, 0),
  ('Laqum', 'laqum-550', '{}', 'contacto@laqum.cl', 'laqum.cl', '+56 47452479', 'informativo', false, 0),
  ('Laserena', 'laserena-781', '{}', NULL, 'prefabricadassanta.wixsite.com', NULL, 'informativo', false, 0),
  ('Linkhome', 'linkhome-556', '{}', NULL, 'linkhome.cl', NULL, 'informativo', false, 0),
  ('Loow Chile', 'loow-chile-260', '{}', NULL, 'loow.cl', '+56 88185584', 'informativo', false, 0),
  ('Madecas', 'madecas-599', '{Los Lagos}', 'madecascontacto@gmail.com', 'madecas.cl', '+56 7777 0022', 'informativo', false, 0),
  ('Madera21', 'madera21-568', '{O''Higgins}', 'madera21@corma.cl', 'madera21.cl', NULL, 'informativo', false, 0),
  ('Magisur', 'magisur-181', '{}', 'contacto@focosur.cl', 'magisur.cl', '+56 9824 5279', 'informativo', false, 0),
  ('Mediagua Chile', 'mediagua-chile-762', '{Metropolitana}', NULL, 'mediaguachile.cl', '+56 86676329', 'informativo', false, 0),
  ('Megapanel', 'megapanel-71', '{}', 'contacto@megapanel.cl', 'megapanel.cl', '+56 75883000', 'informativo', false, 0),
  ('Mercantil.com El Directorio De Empresas En', 'mercantil-com-el-directorio-de-empresas-en-740', '{Arica y Parinacota}', NULL, NULL, 'Arica y Parinacota', 'informativo', false, 0),
  ('Metalkit', 'metalkit-588', '{}', 'ventas@metalkit.cl', 'metalkit.cl', '+56 5805 6559', 'informativo', false, 0),
  ('Ministerio De Vivienda Y Urbanismo', 'ministerio-de-vivienda-y-urbanismo-400', '{}', NULL, 'minvu.gob.cl', NULL, 'informativo', false, 0),
  ('Misitio 1', 'misitio-1-521', '{}', NULL, 'casasarchipielago.cl', '+56 87526829', 'informativo', false, 0),
  ('Modjourney', 'modjourney-67', '{}', NULL, 'modjourney.cl', NULL, 'informativo', false, 0),
  ('Modular SIP', 'modular-sip-726', '{Metropolitana}', 'ventas@modularsip.cl', 'modularsip.cl', '+56 94872861', 'informativo', false, 0),
  ('Mundo Panel Sip', 'mundo-panel-sip-415', '{O''Higgins}', 'contacto@mundopanelsip.cl', 'mundopanelsip.cl', NULL, 'informativo', false, 0),
  ('Negocio & Construcción', 'negocio-construcci-n-204', '{Metropolitana}', 'contacto@negocioyconstruccion.cl', 'negocioyconstruccion.cl', '+56 73357506', 'informativo', false, 0),
  ('Nehúen Construcciones Modulares', 'neh-en-construcciones-modulares-635', '{}', 'ventas@nehuenmodulares.cl', 'nehuenmodulares.cl', '+56 68318477', 'informativo', false, 0),
  ('Nordhaus', 'nordhaus-255', '{}', 'contacto@nordhaus.cl', 'nordhaus.cl', NULL, 'informativo', false, 0),
  ('Panel SIP Metcorp', 'panel-sip-metcorp-35', '{}', 'contacto@metcorp.cl', 'panelsipmetcorp.cl', '+56 3235 2570', 'informativo', false, 0),
  ('Panelbox', 'panelbox-698', '{Biobío}', 'contacto@panelbox.cl', 'panelbox.cl', '+56 8555 6172', 'informativo', false, 0),
  ('Paneles Sip', 'paneles-sip-713', '{Metropolitana}', '7626ventas@panelessip.cl', 'panelessip.cl', '+56 8668 7626', 'informativo', false, 0),
  ('Paneles SIP En Chile. Calidad Al Mejor Precio', 'paneles-sip-en-chile-calidad-al-mejor-precio-956', '{}', NULL, 'panelsandwich.cl', NULL, 'informativo', false, 0),
  ('Patagonia House Spa', 'patagonia-house-spa-506', '{}', NULL, 'patagoniahouse.cl', NULL, 'informativo', false, 0),
  ('Patagual Home', 'patagual-home-445', '{}', 'contacto@patagualhome.cl', 'patagualhome.cl', NULL, 'informativo', false, 0),
  ('Pinterest', 'pinterest-238', '{}', NULL, 'in.pinterest.com', NULL, 'informativo', false, 0),
  ('Pintores Chiloé', 'pintores-chilo-738', '{Los Lagos}', 'hola@pintoreschiloe.cl', 'pintoreschiloe.cl', '+56 4054 7785', 'informativo', false, 0),
  ('Planos De Casas', 'planos-de-casas-749', '{Metropolitana}', 'contacto@planosdecasas.cl', 'planosdecasas.cl', '+56 50304351', 'informativo', false, 0),
  ('Prefabricada', 'prefabricada-774', '{}', 'contacto@prefabricada.cl', 'prefabricada.cl', '+56 97127179', 'informativo', false, 0),
  ('Prefabricadas Premium', 'prefabricadas-premium-703', '{Coquimbo}', 'contacto@prefabricadaspremium.cl', 'prefabricadaspremium.cl', '+56 8983 7171', 'informativo', false, 0),
  ('Prefabricadas San Ignacio', 'prefabricadas-san-ignacio-656', '{Biobío}', 'contacto@prefabricadassanignacio.cl', 'prefabricadassanignacio.cl', NULL, 'informativo', false, 0),
  ('Prefabricadosrya', 'prefabricadosrya-482', '{O''Higgins}', 'contacto@prefabricadosrya.cl', 'prefabricadosrya.cl', '+56 87285303', 'informativo', false, 0),
  ('Prefabs', 'prefabs-996', '{Metropolitana}', 'contacto@prefabs.cl', 'prefabs.cl', '+56 4629 0610', 'informativo', false, 0),
  ('Promet', 'promet-800', '{}', 'ventas@promet.cl', 'promet.cl', '+56 22899915', 'informativo', false, 0),
  ('Propanel', 'propanel-681', '{}', 'contacto@propanel.cl', 'propanel.cl', '+56 3011 3181', 'informativo', false, 0),
  ('Prosip', 'prosip-443', '{}', NULL, 'prosip.cl', '+56 3754 0278', 'informativo', false, 0),
  ('Ready House', 'ready-house-987', '{}', 'ventas@readyhouse.cl', 'readyhouse.cl', '+56 5149 6508', 'informativo', false, 0),
  ('Refugios Nativos', 'refugios-nativos-555', '{}', 'info@refugiosnativos.cl', 'refugiosnativos.cl', '+56 4429 2000', 'informativo', false, 0),
  ('Ruca Llapüd', 'ruca-llap-d-311', '{Ñuble}', NULL, 'rucallapud.cl', '+56 71799610', 'informativo', false, 0),
  ('Rucantu', 'rucantu-22', '{Metropolitana}', 'chilecontacto@rucantu.cl', 'rucantu.cl', NULL, 'informativo', false, 0),
  ('Rukalhue', 'rukalhue-629', '{}', NULL, 'casasrukalhue.cl', NULL, 'informativo', false, 0),
  ('Ruralhouse', 'ruralhouse-619', '{}', 'contactoruralhouse@gmail.com', 'ruralhouse.cl', '+56 4456 2666', 'informativo', false, 0),
  ('Ruralistic', 'ruralistic-444', '{}', 'ruralistic24@gmail.com', 'ruralistic.cl', NULL, 'informativo', false, 0),
  ('Servipro', 'servipro-816', '{}', 'contacto@servipro.cl', 'servipro.cl', '+56 5702 3353', 'informativo', false, 0),
  ('Siphouse', 'siphouse-756', '{Metropolitana}', 'ventas@siphouse.cl', 'siphouse.cl', '+56 5406 6425', 'informativo', false, 0),
  ('Sitio Web Nativos Chile', 'sitio-web-nativos-chile-561', '{}', 'ventas@casasnativoschile.cl', 'casasnativoschile.cl', '+56 59126865', 'informativo', false, 0),
  ('Slaico Lab', 'slaico-lab-443', '{}', 'slaicospa@gmail.com', 'slaico.cl', NULL, 'informativo', false, 0),
  ('Soloprefabricadas', 'soloprefabricadas-674', '{La Araucanía}', NULL, 'soloprefabricadas.cl', NULL, 'informativo', false, 0),
  ('Spacewise', 'spacewise-96', '{}', 'ventas@spacewise.cl', 'spacewise.cl', NULL, 'informativo', false, 0),
  ('Steelframing', 'steelframing-412', '{}', 'contacto@casasgreenvalley.cl', 'steelframing.cl', '+56 2583 2001', 'informativo', false, 0),
  ('Sweethomes Chile', 'sweethomes-chile-465', '{}', 'n.ventas@sweethomes.cl', 'sweethomes.cl', '+56 5334 7939', 'informativo', false, 0),
  ('Talca Prefabricadas', 'talca-prefabricadas-300', '{Maule}', 'contacto@talcaprefabricadas.cl', 'talcaprefabricadas.cl', '+56 7596 6631', 'informativo', false, 0),
  ('Talehome', 'talehome-809', '{}', NULL, 'talehome.cl', NULL, 'informativo', false, 0),
  ('TECHO Chile', 'techo-chile-634', '{}', 'info.chile@techo.org', 'cl.techo.org', '+56 2838 7300', 'informativo', false, 0),
  ('Tecna Zinc', 'tecna-zinc-400', '{}', 'contacto@tecna-zinc.cl', 'tecna-zinc.cl', '+56 27792544', 'informativo', false, 0),
  ('Tecno Fast', 'tecno-fast-979', '{}', 'cotizaciones@tecnofast.cl', 'tecnofast.cl', '+56 27905000', 'informativo', false, 0),
  ('Tecno Fast Home', 'tecno-fast-home-581', '{}', NULL, 'tecnofasthome.cl', NULL, 'informativo', false, 0),
  ('Tecnopanel', 'tecnopanel-106', '{Metropolitana}', 'contacto@iterrasur.cl', 'tecnopanel.cl', '+56 2745 5940', 'informativo', false, 0),
  ('Temukit', 'temukit-899', '{La Araucanía}', 'contacto@temukit.cl', 'temukit.cl', '+56 41789790', 'informativo', false, 0),
  ('The Wall', 'the-wall-704', '{}', 'ventas@thewall.cl', 'thewall.cl', '+56 9632 1615', 'informativo', false, 0),
  ('Tiny Home', 'tiny-home-937', '{}', 'nventas@tiny-home.cl', 'tiny-home.cl', '+56 6473 8781', 'informativo', false, 0),
  ('Tiny Paihuen', 'tiny-paihuen-642', '{}', NULL, 'tinypaihuen.cl', NULL, 'informativo', false, 0),
  ('Trupanel', 'trupanel-869', '{}', 'trupanel@trupanel.cl', 'trupanel.cl', '+56 9430 2618', 'informativo', false, 0),
  ('Trupanel Casas SIP', 'trupanel-casas-sip-614', '{}', NULL, 'casassip.cl', '+56 9430 2618', 'informativo', false, 0),
  ('Tu Casa Fácil', 'tu-casa-f-cil-0', '{Metropolitana}', 'ventas@tucasafacil.cl', 'tucasafacil.cl', '+56 3009 4515', 'informativo', false, 0),
  ('Vaspanel', 'vaspanel-610', '{}', 'info@vaspanel.cl', 'vaspanel.cl', NULL, 'informativo', false, 0),
  ('VH Aceros', 'vh-aceros-596', '{}', 'ventas@vh.cl', 'vhaceros.cl', '+56 2462 6900', 'informativo', false, 0),
  ('Vidrierías En Quilpué Por Vidriería Chimy', 'vidrier-as-en-quilpu-por-vidrier-a-chimy-684', '{Valparaíso}', NULL, 'vidrieriachimy.cl', NULL, 'informativo', false, 0),
  ('Viviendas Aconcagua', 'viviendas-aconcagua-566', '{Valparaíso}', NULL, 'viviendasaconcagua.com', NULL, 'informativo', false, 0),
  ('Viviendas Modulares En Chile', 'viviendas-modulares-en-chile-851', '{Metropolitana}', NULL, 'ayma.cl', NULL, 'informativo', false, 0);
