-- Script de carga automática para constructoras scrapeadas de Google Maps
-- Ejecutar en Supabase Dashboard: SQL Editor -> New query -> Run

-- 1. Asegurar columnas de coordenadas
ALTER TABLE public.constructoras ADD COLUMN IF NOT EXISTS lat DOUBLE PRECISION;
ALTER TABLE public.constructoras ADD COLUMN IF NOT EXISTS lng DOUBLE PRECISION;

-- 2. Asegurar índice único en slug para permitir ON CONFLICT (slug)
CREATE UNIQUE INDEX IF NOT EXISTS constructoras_slug_key ON public.constructoras (slug);

-- 3. Insertar / Actualizar constructoras
INSERT INTO public.constructoras (
  nombre,
  slug,
  descripcion,
  direccion,
  telefono,
  sitio_web,
  lat,
  lng,
  plan,
  verificada,
  score_confianza,
  regiones
) VALUES
  ('Casas Prefabricadas METALKIT', 'casas-prefabricadas-metalkit', 'Fabricante y constructora de casas en Chile. Ubicación: Casas Prefabricadas METALKIT - Caletera Poniente, Ruta 5, Km 39,5, Paine, Región Metropolitana.', 'Casas Prefabricadas METALKIT - Caletera Poniente, Ruta 5, Km 39,5, Paine, Región Metropolitana', '9 5805 6559', 'https://www.metalkit.cl/', -33.7797611, -70.7454274, 'informativo', false, 88, ARRAY['Metropolitana']::text[]),
  ('CASAS PREFABRICADAS Metalcon, modelos- Llave en mano en Santiago', 'casas-prefabricadas-metalcon-modelos--llave-en-mano-en-santiago', 'Fabricante y constructora de casas en Chile. Ubicación: CASAS PREFABRICADAS Metalcon, modelos- Llave en mano en Santiago - Av. Américo Vespucio 744, 7980711 La Cisterna, Región Metropolitana.', 'CASAS PREFABRICADAS Metalcon, modelos- Llave en mano en Santiago - Av. Américo Vespucio 744, 7980711 La Cisterna, Región Metropolitana', '(2) 2310 5779', 'http://www.casasamerica.cl/', -33.5388923, -70.655438, 'informativo', false, 56, ARRAY['Metropolitana']::text[]),
  ('Tecno Fast - Santiago', 'tecno-fast---santiago', 'Fabricante y constructora de casas en Chile. Ubicación: Metropolitana.', NULL, '9 3469 5135', 'http://www.tecnofast.cl/', NULL, NULL, 'informativo', false, 77, ARRAY['Metropolitana']::text[]),
  ('Casas Prefabricadas El Alba', 'casas-prefabricadas-el-alba', 'Fabricante y constructora de casas en Chile. Ubicación: Casas Prefabricadas El Alba - Av. Calera de Tango, Parcela 8-C, Comuna, San Bernardo, Región Metropolitana.', 'Casas Prefabricadas El Alba - Av. Calera de Tango, Parcela 8-C, Comuna, San Bernardo, Región Metropolitana', '9 3184 6889', 'https://www.prefabricadaselalba.cl/', -33.630063, -70.72214009999999, 'informativo', false, 79, ARRAY['Metropolitana']::text[]),
  ('Casas Prefabricadas Modulares', 'casas-prefabricadas-modulares', 'Fabricante y constructora de casas en Chile. Ubicación: Casas Prefabricadas Modulares - Los Dominicos 8630, of. 311, 7571892 Las Condes, Región Metropolitana.', 'Casas Prefabricadas Modulares - Los Dominicos 8630, of. 311, 7571892 Las Condes, Región Metropolitana', '9 9712 7179', 'http://www.prefabricada.cl/', -33.409732999999996, -70.5446042, 'informativo', false, 72, ARRAY['Metropolitana']::text[]),
  ('Casas Chile', 'casas-chile', 'Fabricante y constructora de casas en Chile. Ubicación: Casas Chile - Av. Pdte. Jorge Alessandri Rodríguez 19679, San Bernardo, Región Metropolitana.', 'Casas Chile - Av. Pdte. Jorge Alessandri Rodríguez 19679, San Bernardo, Región Metropolitana', '9 2732 2634', 'http://www.casaschilespa.cl/', -33.625129199999996, -70.7157592, 'informativo', false, 70, ARRAY['Metropolitana']::text[]),
  ('CASAS VESPUCIO, Casas Prefabricadas en Chile', 'casas-vespucio-casas-prefabricadas-en-chile', 'Fabricante y constructora de casas en Chile. Ubicación: CASAS VESPUCIO, Casas Prefabricadas en Chile - Brisas del Maipo 36, Santiago, La Cisterna, Región Metropolitana.', 'CASAS VESPUCIO, Casas Prefabricadas en Chile - Brisas del Maipo 36, Santiago, La Cisterna, Región Metropolitana', '(2) 2312 8415', 'https://www.casasvespucio.cl/', -33.533122899999995, -70.6641058, 'informativo', false, 90, ARRAY['Metropolitana']::text[]),
  ('Construcciones Y&P', 'construcciones-yp', 'Fabricante y constructora de casas en Chile. Ubicación: Construcciones Y&P - Grumete Pantaleón Cortés 21101, 8380000 Santiago, Independencia, Región Metropolitana.', 'Construcciones Y&P - Grumete Pantaleón Cortés 21101, 8380000 Santiago, Independencia, Región Metropolitana', '9 2957 7844', NULL, -33.4087603, -70.6733802, 'informativo', false, 90, ARRAY['Metropolitana']::text[]),
  ('Tecno Fast', 'tecno-fast', 'Fabricante y constructora de casas en Chile. Ubicación: Tecno Fast - Av. Pdte. Eduardo Frei Montalva 17000, Colina, Región Metropolitana.', 'Tecno Fast - Av. Pdte. Eduardo Frei Montalva 17000, Colina, Región Metropolitana', '(2) 2790 5000', 'https://tecnofasthome.cl/', -33.309044, -70.7252475, 'informativo', false, 79, ARRAY['Metropolitana']::text[]),
  ('Casas Prefabricadas Chile', 'casas-prefabricadas-chile', 'Fabricante y constructora de casas en Chile. Ubicación: Metropolitana.', NULL, '9 4498 3013', 'https://casasprefabricadasenchile.com/', -33.472788, -70.62983129999999, 'informativo', false, 90, ARRAY['Metropolitana']::text[]),
  ('Casas Prefabricadas La Hacienda Metalcon', 'casas-prefabricadas-la-hacienda-metalcon', 'Fabricante y constructora de casas en Chile. Ubicación: Casas Prefabricadas La Hacienda Metalcon - Calera de Tango Parcela 8 lado norte calera de tango, parcela 8C, 9560000 San Bernardo, Región Metropolitana.', 'Casas Prefabricadas La Hacienda Metalcon - Calera de Tango Parcela 8 lado norte calera de tango, parcela 8C, 9560000 San Bernardo, Región Metropolitana', '9 5699 8763', 'https://www.casaslahacienda.cl/servicios/', -33.6298023, -70.7212687, 'informativo', false, 76, ARRAY['Metropolitana']::text[]),
  ('Casas Prefabricadas Caballero', 'casas-prefabricadas-caballero', 'Fabricante y constructora de casas en Chile. Ubicación: Casas Prefabricadas Caballero - Av. Américo Vespucio 744, 7980711 La Cisterna, Región Metropolitana.', 'Casas Prefabricadas Caballero - Av. Américo Vespucio 744, 7980711 La Cisterna, Región Metropolitana', '(2) 2310 5779', 'http://www.casascaballero.cl/', -33.5388923, -70.655438, 'informativo', false, 90, ARRAY['Metropolitana']::text[]),
  ('Casas Latam', 'casas-latam', 'Fabricante y constructora de casas en Chile. Ubicación: Casas Latam - Cauquenes 6130, 9080072 Santiago, Cerro Navia, Región Metropolitana.', 'Casas Latam - Cauquenes 6130, 9080072 Santiago, Cerro Navia, Región Metropolitana', NULL, NULL, -33.427599, -70.7202798, 'informativo', false, 72, ARRAY['Metropolitana']::text[]),
  ('Casas Prefabricadas Calera de Tango', 'casas-prefabricadas-calera-de-tango', 'Fabricante y constructora de casas en Chile. Ubicación: Casas Prefabricadas Calera de Tango - Av. Calera de Tango 19, San Bernardo, Región Metropolitana.', 'Casas Prefabricadas Calera de Tango - Av. Calera de Tango 19, San Bernardo, Región Metropolitana', '9 5848 9227', 'https://casaprefabricadachile.cl/calera-de-tango/', -33.6317108, -70.72552929999999, 'informativo', false, 63, ARRAY['Metropolitana']::text[]),
  ('Estructuras green Valley SPA.', 'estructuras-green-valley-spa', 'Fabricante y constructora de casas en Chile. Ubicación: ESQ SN - J ALESSANDRI, San José de Nos KM 24, LT 2, 8050000 San Bernardo, Región Metropolitana.', 'ESQ SN - J ALESSANDRI, San José de Nos KM 24, LT 2, 8050000 San Bernardo, Región Metropolitana', '(2) 2583 2001', 'https://cprefabricadas.cl/', -33.6344098, -70.7133676, 'informativo', false, 90, ARRAY['Metropolitana']::text[]),
  ('Casas prefabricadas NYF', 'casas-prefabricadas-nyf', 'Fabricante y constructora de casas en Chile. Ubicación: Casas prefabricadas NYF - Ciencias 8585, 7970635 La Cisterna, Región Metropolitana.', 'Casas prefabricadas NYF - Ciencias 8585, 7970635 La Cisterna, Región Metropolitana', '9 7479 9445', 'http://www.casasnyf.cl/', -33.5323734, -70.6692295, 'informativo', false, 81, ARRAY['Metropolitana']::text[]),
  ('Casas Santiago', 'casas-santiago', 'Fabricante y constructora de casas en Chile. Ubicación: Casas Santiago - Av. Calera de Tango, 9560000 Calera de Tango, San Bernardo, Región Metropolitana.', 'Casas Santiago - Av. Calera de Tango, 9560000 Calera de Tango, San Bernardo, Región Metropolitana', '9 8805 8335', NULL, -33.6281891, -70.7165179, 'informativo', false, 76, ARRAY['Metropolitana']::text[]),
  ('Tu Casa Fácil', 'tu-casa-facil', 'Fabricante y constructora de casas en Chile. Ubicación: Tu Casa Fácil - Alessandri Rodríguez 20185 (Terreno 01), San Bernardo, Región, San Bernardo, Región Metropolitana.', 'Tu Casa Fácil - Alessandri Rodríguez 20185 (Terreno 01), San Bernardo, Región, San Bernardo, Región Metropolitana', '9 3009 4515', 'https://tucasafacil.cl/', -33.6359232, -70.71307759999999, 'informativo', false, 81, ARRAY['Metropolitana']::text[]),
  ('Casas Alvarado S.P.A.', 'casas-alvarado-spa', 'Fabricante y constructora de casas en Chile. Ubicación: Casas Alvarado S.P.A. - Caletera San Martín, Av. Chicureo Oriente, Parcela 20, 9340000 Colina, Región Metropolitana.', 'Casas Alvarado S.P.A. - Caletera San Martín, Av. Chicureo Oriente, Parcela 20, 9340000 Colina, Región Metropolitana', '9 4162 9375', 'https://casasalvarado.cl/', -33.257576, -70.6978602, 'informativo', false, 79, ARRAY['Metropolitana']::text[]),
  ('Casas Arbolito Santiago', 'casas-arbolito-santiago', 'Fabricante y constructora de casas en Chile. Ubicación: Casas Arbolito Santiago - Ruta 5 Km 40, Km 40, Paine, Región Metropolitana.', 'Casas Arbolito Santiago - Ruta 5 Km 40, Km 40, Paine, Región Metropolitana', '9 7335 1397', 'http://www.casasarbolito.cl/', -33.7787431, -70.7440534, 'informativo', false, 76, ARRAY['Metropolitana']::text[]),
  ('Casas Prefabricadas Home Easy', 'casas-prefabricadas-home-easy', 'Fabricante y constructora de casas en Chile. Ubicación: Casas Prefabricadas Home Easy - Sebastopol 582, 8930737 San Miguel, Región Metropolitana.', 'Casas Prefabricadas Home Easy - Sebastopol 582, 8930737 San Miguel, Región Metropolitana', '9 5829 8811', 'http://www.homeeasy.cl/', -33.5163545, -70.6410075, 'informativo', false, 76, ARRAY['Metropolitana']::text[]),
  ('INDUSTRIALIZADAS', 'industrializadas', 'Fabricante y constructora de casas en Chile. Ubicación: INDUSTRIALIZADAS - Regina Gálvez 285, 8080816 San Bernardo, Región Metropolitana.', 'INDUSTRIALIZADAS - Regina Gálvez 285, 8080816 San Bernardo, Región Metropolitana', NULL, NULL, -33.638505699999996, -70.71174599999999, 'informativo', false, 61, ARRAY['Metropolitana']::text[]),
  ('Casas prefabricadas lo infante spa', 'casas-prefabricadas-lo-infante-spa', 'Fabricante y constructora de casas en Chile. Ubicación: Casas prefabricadas lo infante spa - Av. Pdte. Jorge Alessandri Rodríguez 20, 181, 8050000 San Bernardo, Región Metropolitana.', 'Casas prefabricadas lo infante spa - Av. Pdte. Jorge Alessandri Rodríguez 20, 181, 8050000 San Bernardo, Región Metropolitana', '9 8341 6889', 'http://www.casasloinfante.cl/', -33.639581899999996, -70.71290069999999, 'informativo', false, 74, ARRAY['Metropolitana']::text[]),
  ('CASAS RECABARREN', 'casas-recabarren', 'Fabricante y constructora de casas en Chile. Ubicación: CASAS RECABARREN - Brown Nte. 100, Ofi 310, 7790569 Santiago, Ñuñoa, Región Metropolitana.', 'CASAS RECABARREN - Brown Nte. 100, Ofi 310, 7790569 Santiago, Ñuñoa, Región Metropolitana', '9 7382 8500', 'https://www.casasrecabarren.cl/', -33.454169, -70.591818, 'informativo', false, 79, ARRAY['Metropolitana']::text[]),
  ('Casas Riquelme', 'casas-riquelme', 'Fabricante y constructora de casas en Chile. Ubicación: Casas Riquelme - Av. Américo Vespucio 199, 8000132 La Cisterna, Región Metropolitana.', 'Casas Riquelme - Av. Américo Vespucio 199, 8000132 La Cisterna, Región Metropolitana', '2232295839', NULL, -33.5384259, -70.6622072, 'informativo', false, 74, ARRAY['Metropolitana']::text[]),
  ('Casas Premium', 'casas-premium', 'Fabricante y constructora de casas en Chile. Ubicación: Casas Premium - Av. Chicureo 901 B, Colina, Región Metropolitana.', 'Casas Premium - Av. Chicureo 901 B, Colina, Región Metropolitana', '9 9343 9600', 'http://www.casaspremium.cl/', -33.2853463, -70.6920877, 'informativo', false, 72, ARRAY['Metropolitana']::text[]),
  ('Casas Prefabricadas Paine Sur', 'casas-prefabricadas-paine-sur', 'Fabricante y constructora de casas en Chile. Ubicación: Metropolitana.', NULL, '9 5001 0266', NULL, -33.472788, -70.62983129999999, 'informativo', false, 90, ARRAY['Metropolitana']::text[]),
  ('Casas Prefabricadas Agam', 'casas-prefabricadas-agam', 'Fabricante y constructora de casas en Chile. Ubicación: Casas Prefabricadas Agam - Av. Pdte. Jorge Alessandri Rodríguez, San Bernardo, Región Metropolitana.', 'Casas Prefabricadas Agam - Av. Pdte. Jorge Alessandri Rodríguez, San Bernardo, Región Metropolitana', '9 4617 5456', 'http://www.casasagam.cl/', -33.659399799999996, -70.7172779, 'informativo', false, 81, ARRAY['Metropolitana']::text[]),
  ('Casas Prefabricadas del Lago', 'casas-prefabricadas-del-lago', 'Fabricante y constructora de casas en Chile. Ubicación: Casas Prefabricadas del Lago - Paradero 17, esquina Avda Calera de Tango, Lonquén Nte., 9560007 Calera de Tango, Región Metropolitana.', 'Casas Prefabricadas del Lago - Paradero 17, esquina Avda Calera de Tango, Lonquén Nte., 9560007 Calera de Tango, Región Metropolitana', '9 4595 2922', 'http://www.casasdellago.cl/', -33.624064499999996, -70.7981169, 'informativo', false, 77, ARRAY['Metropolitana']::text[]),
  ('CONSTRUCTORA CASAS Y CASAS SPA', 'constructora-casas-y-casas-spa', 'Fabricante y constructora de casas en Chile. Ubicación: CONSTRUCTORA CASAS Y CASAS SPA - San Diego 1454, local 35B, 8361540 Santiago, Región Metropolitana.', 'CONSTRUCTORA CASAS Y CASAS SPA - San Diego 1454, local 35B, 8361540 Santiago, Región Metropolitana', NULL, 'http://www.casasycasas.cl/', -33.4648082, -70.6477712, 'informativo', false, 88, ARRAY['Metropolitana']::text[]),
  ('Beebox soluciones modulares ltda', 'beebox-soluciones-modulares-ltda', 'Fabricante y constructora de casas en Chile. Ubicación: Beebox soluciones modulares ltda - Ruta 5 5580, Padre las Casas, Padre Las Casas, Araucanía.', 'Beebox soluciones modulares ltda - Ruta 5 5580, Padre las Casas, Padre Las Casas, Araucanía', '(45) 274 0010', 'http://www.beebox.cl/', -38.786062199999996, -72.61496079999999, 'informativo', false, 68, ARRAY['La Araucanía']::text[]),
  ('Casas Fabelsa', 'casas-fabelsa', 'Fabricante y constructora de casas en Chile. Ubicación: Casas Fabelsa - Camino Freire a Villarrica Km. 3 Sector, Los Castaños, Freire, Araucanía.', 'Casas Fabelsa - Camino Freire a Villarrica Km. 3 Sector, Los Castaños, Freire, Araucanía', '9 9453 2937', 'https://ventacasasprefabricadas.cl/casas-prefabricadas-temuco/', -38.9646666, -72.5901899, 'informativo', false, 77, ARRAY['La Araucanía']::text[]),
  ('Casas Prefabricadas Araucanía', 'casas-prefabricadas-araucania', 'Fabricante y constructora de casas en Chile. Ubicación: Metropolitana.', NULL, '9 6214 8435', NULL, -38.4122919, -72.778475, 'informativo', false, 77, ARRAY['Metropolitana']::text[]),
  ('Casas Prefabricadas CASAS IMPERIO', 'casas-prefabricadas-casas-imperio', 'Fabricante y constructora de casas en Chile. Ubicación: Parcela 3 Cruce Linderos - Cam. Longitudinal Ruta 5 Sur, 9500000 Buin, Región Metropolitana.', 'Parcela 3 Cruce Linderos - Cam. Longitudinal Ruta 5 Sur, 9500000 Buin, Región Metropolitana', '9 5652 5203', 'https://www.casasprefabricadasimperio.cl/', -33.7618441, -70.7421584, 'informativo', false, 74, ARRAY['Metropolitana']::text[]),
  ('Casas Prefabricadas Lonquen', 'casas-prefabricadas-lonquen', 'Fabricante y constructora de casas en Chile. Ubicación: Casas Prefabricadas Lonquen - 16211,, Lonquén Nte. 15777, Calera de Tango, Región Metropolitana.', 'Casas Prefabricadas Lonquen - 16211,, Lonquén Nte. 15777, Calera de Tango, Región Metropolitana', '9 9208 0969', 'https://casasprefabricadaslonquen.cl/', -33.6162457, -70.79563929999999, 'informativo', false, 58, ARRAY['Metropolitana']::text[]),
  ('Casas prefabricadas SILS', 'casas-prefabricadas-sils', 'Fabricante y constructora de casas en Chile. Ubicación: Mall Plaza Oeste - Av. Américo Vespucio 1501, 9500000 Cerrillos, Región Metropolitana.', 'Mall Plaza Oeste - Av. Américo Vespucio 1501, 9500000 Cerrillos, Región Metropolitana', '9 5060 3873', 'https://silselect.cl/', -33.516974999999995, -70.71346199999999, 'informativo', false, 18, ARRAY['Metropolitana']::text[]),
  ('Canadian Houses by Casas Deluxe Ltda.', 'canadian-houses-by-casas-deluxe-ltda', 'Fabricante y constructora de casas en Chile. Ubicación: Canadian Houses by Casas Deluxe Ltda. - Gral Flores 127, 7500546 Santiago, Providencia, Región Metropolitana.', 'Canadian Houses by Casas Deluxe Ltda. - Gral Flores 127, 7500546 Santiago, Providencia, Región Metropolitana', '(2) 2235 0501', 'http://www.canadianhouses.cl/', -33.4269956, -70.6191521, 'informativo', false, 81, ARRAY['Metropolitana']::text[]),
  ('Casas Prefabricadas San Alberto', 'casas-prefabricadas-san-alberto', 'Fabricante y constructora de casas en Chile. Ubicación: Casas Prefabricadas San Alberto - Los Acacios 120, 9540569 Paine, Región Metropolitana.', 'Casas Prefabricadas San Alberto - Los Acacios 120, 9540569 Paine, Región Metropolitana', '9 3405 5282', 'https://casasanalberto.com/', -33.861284999999995, -70.7321101, 'informativo', false, 90, ARRAY['Metropolitana']::text[]),
  ('Casas Don Carlos', 'casas-don-carlos', 'Fabricante y constructora de casas en Chile. Ubicación: Casas Don Carlos - Av. Calera de Tango, Calera de Tango, Peñaflor, Región Metropolitana.', 'Casas Don Carlos - Av. Calera de Tango, Calera de Tango, Peñaflor, Región Metropolitana', '44 293 9335', NULL, -33.6273267, -70.7687873, 'informativo', false, 81, ARRAY['Metropolitana']::text[]),
  ('Casas VAL', 'casas-val', 'Fabricante y constructora de casas en Chile. Ubicación: Casas VAL - Cam. A Melipilla - El Monte 1694, El Monte, Región Metropolitana.', 'Casas VAL - Cam. A Melipilla - El Monte 1694, El Monte, Región Metropolitana', '(2) 3346 5556', 'http://www.casasval.cl/', -33.688997, -71.0435902, 'informativo', false, 77, ARRAY['Metropolitana']::text[]),
  ('Casas Prefabricadas Ordenes Construcciones', 'casas-prefabricadas-ordenes-construcciones', 'Fabricante y constructora de casas en Chile. Ubicación: Casas Prefabricadas Ordenes Construcciones - Lonquen Sur 35, 9560000 Talagante, Región Metropolitana.', 'Casas Prefabricadas Ordenes Construcciones - Lonquen Sur 35, 9560000 Talagante, Región Metropolitana', '(2) 2914 6005', 'https://www.ordenesconstrucciones.cl/', -33.6827343, -70.851216, 'informativo', false, 81, ARRAY['Metropolitana']::text[]),
  ('Casas Prefabricadas Alihuen', 'casas-prefabricadas-alihuen', 'Fabricante y constructora de casas en Chile. Ubicación: Casas Prefabricadas Alihuen - Av. Calera de Tango, 8820000 Calera de Tango, San Bernardo, Región Metropolitana.', 'Casas Prefabricadas Alihuen - Av. Calera de Tango, 8820000 Calera de Tango, San Bernardo, Región Metropolitana', '9 3653 9591', 'https://casasprefabricadasalihuen.cl/', -33.6317768, -70.7268103, 'informativo', false, 90, ARRAY['Metropolitana']::text[]),
  ('Casas Prefabricadas Josepha SpA.', 'casas-prefabricadas-josepha-spa', 'Fabricante y constructora de casas en Chile. Ubicación: Casas Prefabricadas Josepha SpA. - Francisco Javier Krugger 3300, 9501957 Buin, Región Metropolitana.', 'Casas Prefabricadas Josepha SpA. - Francisco Javier Krugger 3300, 9501957 Buin, Región Metropolitana', '9 3751 1420', 'https://www.josepha.cl/', -33.7561222, -70.73549779999999, 'informativo', false, 90, ARRAY['Metropolitana']::text[]),
  ('CONSTRUKIT - Casas Industrializadas de Alto Estándar', 'construkit---casas-industrializadas-de-alto-estandar', 'Fabricante y constructora de casas en Chile. Ubicación: CONSTRUKIT - Casas Industrializadas de Alto Estándar - Ruta Panamericana Sur Km. 680, Temuco, Padre Las Casas, Araucanía.', 'CONSTRUKIT - Casas Industrializadas de Alto Estándar - Ruta Panamericana Sur Km. 680, Temuco, Padre Las Casas, Araucanía', NULL, 'http://www.construkit.cl/', -38.7969181, -72.62186299999999, 'informativo', false, 88, ARRAY['La Araucanía']::text[]),
  ('Tiny Homes Chile', 'tiny-homes-chile', 'Fabricante y constructora de casas en Chile. Ubicación: Tiny Homes Chile - Av. Apoquindo 6410, 605, 7560903 Las Condes, Región Metropolitana.', 'Tiny Homes Chile - Av. Apoquindo 6410, 605, 7560903 Las Condes, Región Metropolitana', '9 9129 7505', 'http://www.instagram.com/tinyhomeschile/', -33.407671799999996, -70.5638941, 'informativo', false, 90, ARRAY['Metropolitana']::text[]),
  ('Casas Prefabricadas Sandoval', 'casas-prefabricadas-sandoval', 'Fabricante y constructora de casas en Chile. Ubicación: Casas Prefabricadas Sandoval - Tocornal 7377, 2200000 Valparaíso, Santa María, Valparaíso.', 'Casas Prefabricadas Sandoval - Tocornal 7377, 2200000 Valparaíso, Santa María, Valparaíso', '9 9157 0552', 'https://www.casassandoval.cl/', -32.7734553, -70.6596505, 'informativo', false, 77, ARRAY['Valparaíso']::text[]),
  ('Full Casas Prefabricadas', 'full-casas-prefabricadas', 'Fabricante y constructora de casas en Chile. Ubicación: Full Casas Prefabricadas - Sta. Fe 690, 7980003 San Miguel, Región Metropolitana.', 'Full Casas Prefabricadas - Sta. Fe 690, 7980003 San Miguel, Región Metropolitana', '9 5423 4825', 'http://www.fullcasasprefabricadas.cl/', -33.5146207, -70.6565389, 'informativo', false, 65, ARRAY['Metropolitana']::text[]),
  ('Inmobiliaria Martabid Spa', 'inmobiliaria-martabid-spa', 'Fabricante y constructora de casas en Chile. Ubicación: Inmobiliaria Martabid Spa - C. Las Quilas 1535, 4791797 Temuco, Araucanía.', 'Inmobiliaria Martabid Spa - C. Las Quilas 1535, 4791797 Temuco, Araucanía', '(45) 273 2900', 'http://www.martabid.com/', -38.748791, -72.6050044, 'informativo', false, 70, ARRAY['La Araucanía']::text[]),
  ('Siphouse', 'siphouse', 'Fabricante y constructora de casas en Chile. Ubicación: Parque Industrial - P1-A, Lautaro, Araucanía.', 'Parque Industrial - P1-A, Lautaro, Araucanía', '9 5406 6425', 'http://www.siphouse.cl/', -38.560425699999996, -72.4507465, 'informativo', false, 90, ARRAY['La Araucanía']::text[])
ON CONFLICT (slug) DO UPDATE SET
  direccion = COALESCE(EXCLUDED.direccion, constructoras.direccion),
  telefono = COALESCE(EXCLUDED.telefono, constructoras.telefono),
  sitio_web = COALESCE(EXCLUDED.sitio_web, constructoras.sitio_web),
  lat = COALESCE(EXCLUDED.lat, constructoras.lat),
  lng = COALESCE(EXCLUDED.lng, constructoras.lng),
  score_confianza = GREATEST(EXCLUDED.score_confianza, constructoras.score_confianza);
